import React, { useEffect, useState } from 'react';
import { AbsoluteFill, Img, Sequence, interpolate, useCurrentFrame, staticFile, delayRender, continueRender, cancelRender } from 'remotion';
import { SLIDES, DURATION } from './slides';

const C = { paper:'#fffdfa', peach:'#fbefe6', rust:'#ae3b23', ink:'#192124', muted:'#656762', line:'#dacbc0', dark:'#20352e' };
const asset = (name, base) => base ? `${base}${name}` : staticFile(name);
const ease = t => 1-Math.pow(1-t,3);
const motion = (frame, delay=0) => ({ opacity:interpolate(frame,[delay,delay+20],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}), transform:`translateY(${interpolate(frame,[delay,delay+28],[32,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:ease})}px)` });
const label = { fontSize:21,letterSpacing:3,textTransform:'uppercase',fontWeight:650,color:C.rust,marginBottom:25 };
const heading = { fontSize:88,lineHeight:1.06,letterSpacing:-4,fontWeight:700,margin:0 };
const body = { fontSize:31,lineHeight:1.5,color:C.muted,margin:0 };

function Frame({children,index,dark=false}) {
  const frame=useCurrentFrame();
  return <AbsoluteFill style={{background:dark?C.dark:C.paper,color:dark?C.paper:C.ink,fontFamily:'Inter, sans-serif',padding:'75px 100px 90px'}}>
    <div style={{display:'flex',justifyContent:'space-between',fontSize:22,lineHeight:1.16,letterSpacing:-.5,fontWeight:650,opacity:.9}}><div>Tulsa Housing<br/>Justice Network</div><div style={{fontSize:17,fontWeight:400,letterSpacing:1}}>PARTNERS + PHILANTHROPY</div></div>
    <div style={{position:'absolute',left:100,right:100,top:190,bottom:110}}>{children}</div>
    <div style={{position:'absolute',bottom:42,left:100,right:100,display:'flex',justifyContent:'space-between',fontSize:17,color:dark?'#c4cfc6':'#76756e'}}><span>Fictional workshop concept · Proposed program</span><span>{String(index+1).padStart(2,'0')} / 10</span></div>
    <div style={{position:'absolute',bottom:0,left:0,height:6,background:C.rust,width:`${((SLIDES[index].from+frame)/DURATION)*100}%`}}/>
  </AbsoluteFill>;
}
function Text({children,frame,delay=0,style={}}){return <div style={{...motion(frame,delay),...style}}>{children}</div>;}
function Photo({name,base,frame,style={}}){return <div style={{overflow:'hidden',...style}}><Img src={asset(name,base)} style={{width:'100%',height:'100%',objectFit:'cover',transform:`scale(${1.025+frame*.000055})`}}/></div>;}

function Slide({index,assetBase}){
  const f=useCurrentFrame();
  const dark=index===5;
  let content;
  if(index===0) return <AbsoluteFill style={{background:C.dark,fontFamily:'Inter, sans-serif',color:C.paper}}>
    <Photo name="hero.webp" base={assetBase} frame={f} style={{position:'absolute',inset:0}}/>
    <AbsoluteFill style={{background:'linear-gradient(90deg,rgba(10,22,16,.90),rgba(10,22,16,.62) 40%,rgba(10,22,16,0) 80%)'}}/>
    <div style={{position:'absolute',top:75,left:100,fontSize:25,fontWeight:650,lineHeight:1.14}}>Tulsa Housing<br/>Justice Network</div>
    <div style={{position:'absolute',top:280,left:100,width:1030}}><Text frame={f} style={{...label,color:'#efcbb3'}}>A stronger Tulsa starts with showing up.</Text><Text frame={f} delay={8}><h1 style={{...heading,fontSize:110,letterSpacing:-5}}>More lawyers.<br/>More neighbors.<br/>A way forward.</h1></Text><Text frame={f} delay={24} style={{fontSize:31,lineHeight:1.5,maxWidth:780,marginTop:38}}>A supported path into housing justice.<br/>Free representation for residents.</Text></div>
    <div style={{position:'absolute',bottom:50,left:100,fontSize:18}}>Fictional workshop concept · Tulsa, Oklahoma</div>
  </AbsoluteFill>;
  if(index===1) content=<><Text frame={f} style={label}>The opportunity</Text><Text frame={f} delay={6}><h1 style={heading}>Help starts with<br/>someone ready to serve.</h1></Text><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:80,marginTop:55}}>{[['For residents','A clear path to representation for eviction and housing discrimination.'],['For legal partners','A manageable way to bring their skills into housing justice.']].map(([t,d],i)=><Text frame={f} delay={18+i*10} key={t} style={{borderTop:`2px solid ${C.line}`,paddingTop:32}}><h2 style={{fontSize:40,margin:'0 0 20px',letterSpacing:-1}}>{t}</h2><p style={body}>{d}</p></Text>)}</div><Text frame={f} delay={45} style={{fontFamily:'Newsreader, Georgia, serif',fontSize:46,marginTop:46,color:C.rust}}>The network makes that connection possible.</Text></>;
  if(index===2) content=<><Text frame={f} style={label}>The proposed model</Text><Text frame={f} delay={5}><h1 style={heading}>One network.<br/>A shared commitment.</h1></Text><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:44,marginTop:65}}>{[['01','Law firms','Licensed attorneys','Pro bono or paid commitments.'],['02','Law schools','A supervised pipeline','Clinics, faculty, and students.'],['03','Local philanthropy','Sustained capacity','Paid work and program support.']].map(([n,t,b,d],i)=><Text frame={f} delay={20+i*12} key={n} style={{borderTop:`3px solid ${C.rust}`,paddingTop:25}}><div style={{fontSize:24,color:C.rust,marginBottom:22}}>{n}</div><h2 style={{fontSize:43,letterSpacing:-1,margin:'0 0 20px'}}>{t}</h2><div style={{fontSize:29,fontWeight:600,marginBottom:12}}>{b}</div><p style={{...body,fontSize:28}}>{d}</p></Text>)}</div></>;
  if(index===3||index===4){const school=index===4;content=<div style={{display:'grid',gridTemplateColumns:'1.08fr 1fr',gap:65,height:'100%'}}><div><Text frame={f} style={label}>{school?'For law schools':'For law firms'}</Text><Text frame={f} delay={7}><h1 style={{...heading,fontSize:77}}>{school?<>Prepare the next<br/>generation<br/>of advocates.</>:<>Bring your<br/>expertise.<br/>Choose your role.</>}</h1></Text><Text frame={f} delay={22} style={{marginTop:32,...body,fontSize:29}}>{school?'Connect learning, mentorship, and service through supervised participation.':'Explore a commitment that fits your team’s capacity and experience.'}</Text><div style={{display:'flex',gap:16,flexWrap:'wrap',marginTop:35}}>{(school?['Clinics','Faculty mentors','Supervised students']:['Pro bono','Paid commitments','Or both']).map((t,i)=><Text key={t} frame={f} delay={35+i*9} style={{fontSize:23,border:`1px solid ${C.line}`,padding:'13px 20px',background:C.peach}}>{t}</Text>)}</div>{!school&&<Text frame={f} delay={68} style={{fontSize:23,color:C.rust,marginTop:25}}>Paid by local philanthropy. Never by residents.</Text>}</div><Photo name={school?'school-team.webp':'firm-team.webp'} base={assetBase} frame={f} style={{height:690,marginTop:0,borderRadius:4}}/></div>;}
  if(index===5) content=<><Text frame={f} style={{...label,color:'#edb69b'}}>Recruitment is the beginning</Text><Text frame={f} delay={6}><h1 style={{...heading,fontFamily:'Newsreader, Georgia, serif',fontWeight:400,fontSize:106,letterSpacing:-3}}>Give people reasons to stay.</h1></Text><Text frame={f} delay={18} style={{...body,color:'#d5ded6',marginTop:26}}>Support the people doing the work.</Text><div style={{marginTop:65}}>{[['Practical training','Build confidence before the first commitment.'],['Experienced mentors','Make room for guidance and peer connection.'],['Manageable commitments','Adapt participation as capacity changes.']].map(([t,d],i)=><Text key={t} frame={f} delay={30+i*16} style={{display:'grid',gridTemplateColumns:'550px 1fr',gap:40,padding:'26px 0',borderTop:'1px solid #637069'}}><span style={{fontSize:39,letterSpacing:-1}}>{t}</span><span style={{fontSize:29,color:'#d5ded6',paddingTop:6}}>{d}</span></Text>)}</div></>;
  if(index===6){const phase=f<110?0:f<220?1:2;const titles=['Request help','Review the request','Connect with representation'];content=<><Text frame={f} style={label}>The resident journey · Working website demo</Text><Text frame={f} delay={5}><h1 style={{...heading,fontSize:77}}>From a request to a connection.</h1></Text><div style={{display:'grid',gridTemplateColumns:'550px 1fr',gap:65,marginTop:42}}><div>{titles.map((t,i)=><div key={t} style={{padding:'22px 0',borderTop:`2px solid ${i===phase?C.rust:C.line}`,opacity:i<=phase?1:.45}}><div style={{fontSize:19,color:C.rust,marginBottom:8}}>0{i+1}</div><h2 style={{fontSize:32,margin:0,letterSpacing:-.7}}>{t}</h2></div>)}<p style={{fontSize:22,lineHeight:1.45,color:C.muted,marginTop:25}}>Live service would require intake review, conflict checks, availability, and acceptance.</p></div><div style={{height:530,overflow:'hidden',border:`1px solid ${C.line}`,boxShadow:'0 14px 45px #382c1814',background:'#fff'}}><Img src={asset(['demo-request.png','demo-review.png','demo-match.png'][phase],assetBase)} style={{width:'100%',height:'100%',objectFit:'cover',objectPosition:'top'}}/></div></div><div style={{fontSize:19,color:C.rust,marginTop:18,textAlign:'right'}}>Simulated matching. No requests are sent.</div></>;}
  if(index===7) content=<><Text frame={f} style={label}>For local philanthropic supporters</Text><Text frame={f} delay={6}><h1 style={heading}>Local generosity.<br/>Legal help at no cost.</h1></Text><div style={{display:'grid',gridTemplateColumns:'550px 1fr',gap:100,marginTop:42}}><Text frame={f} delay={20} style={{background:C.peach,padding:'30px 55px',height:365}}><div style={{fontFamily:'Newsreader, Georgia, serif',fontSize:190,lineHeight:1.05,color:C.rust}}>$0</div><div style={{fontSize:32}}>Cost to residents</div><div style={{fontSize:21,color:C.muted,marginTop:12}}>Under the proposed program</div></Text><div>{['Paid attorney commitments','Training and mentorship','Intake and coordination'].map((t,i)=><Text frame={f} delay={27+i*15} key={t} style={{fontSize:37,padding:'24px 0',borderBottom:`1px solid ${C.line}`}}>{t}</Text>)}<Text frame={f} delay={78} style={{fontSize:25,color:C.muted,marginTop:26}}>Volunteer service adds capacity alongside funded work.</Text></div></div></>;
  if(index===8) content=<><Text frame={f} style={label}>A proposed first step</Text><Text frame={f} delay={6}><h1 style={heading}>Start focused.<br/>Learn. Grow.</h1></Text><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:46,marginTop:50}}>{[['01','Convene','Bring founding firms, schools, and funders together.'],['02','Prepare','Define scope, supervision, intake, and readiness.'],['03','Learn','Pilot with a first cohort and improve the experience.']].map(([n,t,d],i)=><Text key={t} frame={f} delay={20+i*15} style={{borderTop:`3px solid ${C.rust}`,paddingTop:24}}><div style={{fontSize:22,color:C.rust}}>{n}</div><h2 style={{fontSize:42,margin:'15px 0'}}>{t}</h2><p style={{...body,fontSize:29}}>{d}</p></Text>)}</div><Text frame={f} delay={72} style={{marginTop:50,fontSize:25,color:C.rust}}>Track participation, connections, resident experience, and attorney retention.</Text></>;
  if(index===9) content=<div style={{display:'grid',gridTemplateColumns:'1.3fr .8fr',gap:60,height:'100%'}}><div><Text frame={f} style={label}>An invitation to partners + funders</Text><Text frame={f} delay={7}><h1 style={{...heading,fontSize:96}}>Bring your people.<br/>Back the work.</h1></Text><Text frame={f} delay={22} style={{...body,fontSize:30,marginTop:35}}>Law firms + law schools: explore a partnership.<br/>Local philanthropy: help support a pilot.</Text><Text frame={f} delay={40} style={{fontFamily:'Newsreader, Georgia, serif',fontSize:46,color:C.rust,marginTop:42}}>A stronger Tulsa starts with showing up.</Text><Text frame={f} delay={58} style={{marginTop:38}}><div style={{display:'inline-block',background:C.rust,color:'white',padding:'18px 27px',fontSize:25}}>Explore the working demo</div><div style={{fontSize:26,marginTop:20,fontWeight:600}}>gitnelson.github.io/aspire-workshop/</div></Text></div><Photo name="hero.webp" base={assetBase} frame={f} style={{height:685,borderRadius:4}}/></div>;
  return <Frame index={index} dark={dark}>{content}</Frame>;
}

export function Deck({assetBase}){
  const [handle] = useState(()=>delayRender('Loading brand fonts'));
  useEffect(()=>{
    const fonts=[new FontFace('Inter',`url(${asset('inter-latin.woff2',assetBase)})`,{weight:'100 900'}),new FontFace('Newsreader',`url(${asset('newsreader-latin.woff2',assetBase)})`,{weight:'400 600'})];
    let active=true;
    Promise.all(fonts.map(font=>font.load())).then(loaded=>{loaded.forEach(font=>document.fonts.add(font));if(active)continueRender(handle);}).catch(cancelRender);
    return ()=>{active=false;};
  },[handle,assetBase]);
  return <AbsoluteFill>{SLIDES.map(slide=><Sequence key={slide.index} from={slide.from} durationInFrames={slide.duration}><Slide index={slide.index} assetBase={assetBase}/></Sequence>)}</AbsoluteFill>;
}
