export const FPS = 30;
export const SLIDES = [
  { title: 'More lawyers. More neighbors.', seconds: 8, notes: 'Introduce Tulsa Housing Justice Network: a fictional, locally supported model for recruiting and retaining housing advocates. Our aim is to connect residents facing eviction or housing discrimination with representation at no cost.' },
  { title: 'The opportunity', seconds: 8, notes: 'The challenge this concept addresses is the connection between residents who need housing representation and legal professionals who could help. We are proposing a supported path into this work, rather than claiming a measured shortage or an existing service.' },
  { title: 'One network, shared purpose', seconds: 9, notes: 'Law firms contribute licensed attorneys. Law schools contribute faculty partnerships, clinics, and appropriately supervised student participation. Local philanthropic supporters fund paid commitments and program support. Each has a distinct role in expanding access.' },
  { title: 'Invite law firms in', seconds: 9, notes: 'Firms can express interest in pro bono work, paid commitments, or both. Participation would start with a conversation about capacity, experience, and case fit. Paid does not mean paid by the resident: compensation comes from local philanthropic support.' },
  { title: 'Build the next generation', seconds: 9, notes: 'Law school partnerships create a pipeline through clinics, faculty mentorship, and supervised student participation. The operating program would define appropriate roles and supervision. Students are not presented as independently providing representation.' },
  { title: 'Give people reasons to stay', seconds: 9, notes: 'Recruitment is only the beginning. The proposed retention model includes practical training, experienced mentors, peer connection, and manageable commitments. We would work with partners to define the support needed before taking cases.' },
  { title: 'From request to connection', seconds: 11, notes: 'Show the existing website demo. A resident enters sample information, sees a request awaiting review, and then views a simulated representation match. In a live service, intake review, conflict checks, availability, and acceptance by the attorney and resident would precede a confirmed connection. The prototype sends no requests.' },
  { title: 'What local generosity enables', seconds: 9, notes: 'Philanthropy would fund paid attorney commitments, training and mentorship, and intake coordination. Pro bono contributions add capacity. Residents would not pay. No budget, funding commitments, or partner roster has been secured in this fictional exercise.' },
  { title: 'A focused first step', seconds: 9, notes: 'Propose a bounded pilot rather than a large untested launch: convene founding partners, define service scope and readiness, then learn from a first cohort. Evaluate partner participation, request-to-connection progress, resident experience, and attorney retention. These are proposed measures, not reported results.' },
  { title: 'Bring your people. Back the work.', seconds: 9, notes: 'Invite law firms and law schools to explore a founding partnership, and local philanthropic supporters to discuss supporting a pilot. End by opening the working website. It demonstrates the idea, not an active legal service.' },
].map((slide, index, all) => ({ ...slide, index, from: all.slice(0,index).reduce((sum,s)=>sum+s.seconds*FPS,0), duration: slide.seconds*FPS }));
export const DURATION = SLIDES.reduce((sum,slide)=>sum+slide.duration,0);
